# -*- coding: utf-8 -*-
"""MISTRAL_API_OS_ENV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hjKroz6dXOqXgl28gjbkRO6sXgONZsVd
"""

!pip uninstall opentelemetry-api==1.37.0 opentelemetry-sdk==1.37.0

!pip install opentelemetry-api==1.38.0 opentelemetry-sdk==1.38.0

!pip install mistralai

from mistralai.client import MistralClient

from google.colab import userdata

from mistralai import Mistral
import os

# NEVER hardcode keys (rotate the exposed one!)
#api_key = os.environ["MISTRAL_API_KEY"]
api_key='awmTWmddRP4wkDUQAJfUYey4Vt2BE9qx'
#client=MistralClient(api_key=api_key)

client = Mistral(api_key=api_key)

# List models
models = client.models.list()
for model in models.data:
    print(model.id)